python '3. Sense2Vec - CBOW.py' \
  --lr=3e-3 \
  --bs=2500 \
  --seq_len=11 \
  --epochs=2 \
  --device=cuda:1 \
  --input_corpus=data/postprocessed/ds_full.txt \
  --embeddings_size=40 \
  --target_vectors=50 \
  --mlflow_host=http://192.168.113.181:5000 \
  --mlflow_experiment=Sense2Vec_full_test \
  --model_pickles_dir_path=data/models \
  --dataset_pickle_path=data/datasets \
  --minimal_token_occurences=3
